import { DangerButtton } from "../../buttons";
import {
  Box,
  Checkbox,
  Flex,
  Input,
  Table,
  TableContainer,
  Tbody,
  Td,
  Text,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import React, { useEffect, useState } from "react";
import { AiOutlineSearch } from "react-icons/ai";
import { BsThreeDotsVertical } from "react-icons/bs";
import { MdDelete } from "react-icons/md";
import data from "../../../config/data.json";
import "../index.css";

const Volumes = () => {
  const [volumes, setVolumes] = useState<any[]>([]);
  const [parentCheckBox, setParentCheckbox] = useState(false);
  const [showDelete, setShowDelete] = useState(false);

  useEffect(() => {
    let fetchedVolumes = data.volumes;
    fetchedVolumes = fetchedVolumes.map((volume: any) => {
      volume.checked = false;
      return volume;
    });
    setVolumes(fetchedVolumes);
  }, []);

  useEffect(() => {
    let checked = volumes.filter((volume: any) => volume.checked);
    if (checked.length > 0) {
      setShowDelete(true);

      if (checked.length !== volumes.length) {
        setParentCheckbox(false);
      }

      if (checked.length === volumes.length) {
        setParentCheckbox(true);
      }
    } else {
      setShowDelete(false);
      setParentCheckbox(false);
    }
  }, [volumes]);

  return (
    <Box>
      <Text fontSize={20}>Volumes</Text>
      <Text fontSize="xs" py={2}>
        Volumes are the preferred mechanism for persisting data generated by and
        used by Docker containers.
      </Text>

      <Flex my={8} justifyContent="space-between">
        <Box visibility={showDelete ? "visible" : "hidden"}>
          <DangerButtton />
        </Box>

        <Flex justifyContent="space-evenly" alignItems="center">
          <Flex
            border="1px solid #AEAEAE"
            borderRadius={4}
            justifyContent="space-evenly"
            alignItems="center"
          >
            <Box fontSize="25px" as={AiOutlineSearch} mx={2} />
            <Input
              placeholder="Search"
              height={8}
              border="none"
              focusBorderColor="transparent"
            />
          </Flex>
          <Box fontSize="25px" as={BsThreeDotsVertical} ml={4} />
        </Flex>
      </Flex>

      <Box overflow="auto" minHeight="300px" maxHeight="500px">
        <TableContainer>
          <Table variant="simple">
            <Thead>
              <Tr className="tableHead">
                <Th>
                  <Checkbox
                    isChecked={parentCheckBox}
                    onChange={(e) => {
                      setParentCheckbox(e.target.checked);
                      setVolumes((prev: any) => {
                        prev = prev.map((prev: any) => {
                          prev.checked = e.target.checked;
                          return prev;
                        });
                        return prev;
                      });
                    }}
                  />
                </Th>
                <Th>Name</Th>
                <Th>Status</Th>
                <Th>Created</Th>
                <Th>Size</Th>
                <Th>Actions</Th>
              </Tr>
            </Thead>
            <Tbody>
              {volumes.map((volume: any) => {
                return (
                  <Tr key={volume._id}>
                    <Td>
                      <Checkbox
                        isChecked={volume.checked}
                        onChange={(e) => {
                          setVolumes((prev: any) => {
                            prev = prev.map((prev: any) => {
                              if (prev._id === volume._id) {
                                prev.checked = e.target.checked;
                              }
                              return prev;
                            });
                            return prev;
                          });
                        }}
                      />
                    </Td>
                    <Td>{volume._id}</Td>
                    <Td>{volume.status ? volume.status : "-"}</Td>
                    <Td>{volume.created ? volume.created : "-"}</Td>
                    <Td>{volume.size}</Td>
                    <Td>
                      <Flex>
                        <Box
                          fontSize="24px"
                          as={MdDelete}
                          mr={3}
                          pr={2}
                          pb={1}
                        />
                      </Flex>
                    </Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        </TableContainer>
      </Box>
    </Box>
  );
};

export default Volumes;
